language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: SYMFONY_VERSION=^3.0@dev
    - php: 7.1
      env: SYMFONY_VERSION=^4.0
    - php: 7.1
      env: SYMFONY_VERSION=^4.0@dev
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update
  - if [ "$COMPOSER_FLAGS" == "--prefer-lowest" ]; then composer require "roave/security-advisories" dev-master --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
